aws.dynamodb.table-name=CloudBudgetTable

quarkus.dynamodb.aws.region=us-east-1

%dev.quarkus.dynamodb.endpoint-override=http://localhost:4566
%dev.quarkus.dynamodb.aws.credentials.type=static
%dev.quarkus.dynamodb.aws.credentials.static-provider.access-key-id=test
%dev.quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=test

mp.jwt.verify.issuer=http://localhost:8081/realms/budget-realm

mp.jwt.verify.publickey.location=http://localhost:8081/realms/budget-realm/protocol/openid-connect/certs



