# --- CONFIGURAÇÕES DO DYNAMODB ---
aws.dynamodb.table-name=CloudBudgetTable
quarkus.dynamodb.aws.region=us-east-1
%dev.quarkus.dynamodb.endpoint-override=http://localhost:4566
%dev.quarkus.dynamodb.aws.credentials.type=static
%dev.quarkus.dynamodb.aws.credentials.static-provider.access-key-id=test
%dev.quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=test

# --- CONFIGURAÇÕES DE AUTENTICAÇÃO (KEYCLOAK) ---
mp.jwt.verify.issuer=http://localhost:8081/realms/budget-realm
mp.jwt.verify.publickey.location=http://localhost:8081/realms/budget-realm/protocol/openid-connect/certs

# --- CONFIGURAÇÕES DE MENSAGERIA (SNS / SQS) ---
aws.sns.expense-alert-topic-arn=arn:aws:sns:us-east-1:000000000000:expense-alerts-topic

# Configurações do Cliente SNS (Apontando para o Docker local)
%dev.quarkus.sns.endpoint-override=http://localhost:4566
quarkus.sns.aws.region=us-east-1
%dev.quarkus.sns.aws.credentials.type=static
%dev.quarkus.sns.aws.credentials.static-provider.access-key-id=test
%dev.quarkus.sns.aws.credentials.static-provider.secret-access-key=test

# Configurações do Cliente SQS (Apontando para o Docker local)
%dev.quarkus.sqs.endpoint-override=http://localhost:4566
quarkus.sqs.aws.region=us-east-1
%dev.quarkus.sqs.aws.credentials.type=static
%dev.quarkus.sqs.aws.credentials.static-provider.access-key-id=test
%dev.quarkus.sqs.aws.credentials.static-provider.secret-access-key=test

# URL da Fila SQS gerada pelo LocalStack
aws.sqs.expense-alert-queue-url=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/expense-alerts-queue